project:
  type: website
  output-dir: docs

website:
  title: "ETE Notes"
  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: first_semester/index.qmd
        text: First Semester
      - href: second_semester/index.qmd
        text: Second Semester 
      - href: contribute.qmd
        text: Contribute

  sidebar:
    - title: First Semester
      contents: 
        - auto: first_semester

    - title: Second Semester
      contents: 
        - auto: second_semester


format:
  html:
    toc: true
    toc-depth: 4
    theme: cosmo
    css: styles.css



